version: 1.0.{build}

image: Visual Studio 2019

environment:
  matrix:
    - dotnet_version: 3.1.301

init:
  - ps: Install-Product node 12 x64

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

install:
  - cmd: '"%ProgramFiles%\dotnet\dotnet.exe" --version'
  - cmd: '"%ProgramFiles%\dotnet\dotnet.exe" restore'
  - cmd: choco install dotnetcore-sdk --version 3.1.301 -y

build:
  project: NameSorter/NameSorterApp/NameSorterApp.sln

test: 
  assemblies:
    - 'NameSorterApp.UnitTests/bin/**/NameSorterApp.UnitTests.dll'